### ISSUE TITLE
Handle missing packages

### ISSUE THREAD

**Issue by lisroach** [Instagram/Fixit#199]
If there are not `packages` in the config file (or no rules in the packages) we should surface a warning to the user that nothing is going to be run by Fixit.

**Comment by lisroach** [comment]
Forcing a package to not have packages takes a little carwheeling since it really wants to set a default, but when you do remove it you get: 
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/homebrew/Cellar/python37/3.7.5_3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/lisroach/Fixit/fixit/cli/run_rules.py", line 57, in <module>
    get_rules_parser(),
  File "/Users/lisroach/Fixit/fixit/cli/args.py", line 107, in get_rules_parser
    default=get_rules_from_config(),
  File "/Users/lisroach/Fixit/fixit/common/config.py", line 140, in get_rules_from_config
    for package in lint_config.packages:
AttributeError: 'LintConfig' object has no attribute 'packages'
```

Part of my motivation for this is for the inheritable configs, we don't want a config to end up completely invalid with no indication to the end user.

**Comment by lisroach** [comment]
Actually in real world scenarios it looks like it is not possible for packages to be missing, since the default of `fixit.rules` is always set. I'll close this issue.
